In [101]:
import pandas as pd
import numpy as np

In [102]:
#Criando Dicionário

transportadoras = {
    "JSL": 10,
    "TAG": 15,
    "Figma": 25,
}

print(transportadoras)

{'JSL': 10, 'TAG': 15, 'Figma': 25}

In [103]:
# Criando Dataframe

dados_agosto = {
    "Mês": ["Agosto","Agosto","Agosto","Agosto","Agosto","Agosto","Agosto", "Agosto"],
    "Cliente": ["Pernambucanas",None,"Lojas 100","Casas Bahia","Amazon","MELI","LoJas 100", "C_Bahia"],
    "Transportador": ["JSL","TAG","Figma",None,"tag","Jsl","FIGMA","TaG"],
    "Peso": [25,10,20,None,85,30,5,1000],
    "Distância (Km)": [60,15,32,1000,95,20,34,None],
    "Dias_Entrega": [2,5,7,8,15,30,56,72],
    "Status": ["Atrasado","atraAsaso",None,"intregue","Atrasdo","entregue","Entregue","AtraADO"]
}

df_agosto = pd.DataFrame(dados_agosto)
display(df_agosto)

dados_setembro = {
    "Mês": ["Setembro","Setembro","Setembro","Setembro","Setembro","Setembro","Setembro", "Setembro"],
    "Cliente": ["Pernambucanas","Colombo","Lojas 100","Casas Bahia","Amazon","MELI","LoJas 100", "C_Bahia"],
    "Transportador": ["JSL","TAG","Figma",None,"tag","Jsl","FIGMA","TaG"],
    "Peso": [60,10,75,24,45,65,30,50],
    "Distância (Km)": [30,14,20,65,75,64,2,64],
    "Dias_Entrega": [14,20,4,9,8,10,6,4],
    "Status": ["Entregue","atraasado"," Entregue","Atrsdo","entrge","entregue","Entregue","AtraADO"]
}

df_setembro = pd.DataFrame(dados_setembro)
display(df_setembro)

df_geral = pd.concat([df_agosto,df_setembro], axis = 0)
df_geral = df_geral.reset_index(drop=True)
display(df_geral)

,Mês,Cliente,Transportador,Peso,Distância (Km),Dias_Entrega,Status
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado
1,Agosto,NaN,TAG,10.0,15.0,5,atraAsaso
2,Agosto,Lojas 100,Figma,20.0,32.0,7,NaN
3,Agosto,Casas Bahia,NaN,NaN,1000.0,8,intregue
4,Agosto,Amazon,tag,85.0,95.0,15,Atrasdo
5,Agosto,MELI,Jsl,30.0,20.0,30,entregue
6,Agosto,LoJas 100,FIGMA,5.0,34.0,56,Entregue
7,Agosto,C_Bahia,TaG,1000.0,NaN,72,AtraADO

,Mês,Cliente,Transportador,Peso,Distância (Km),Dias_Entrega,Status
0,Setembro,Pernambucanas,JSL,60,30,14,Entregue
1,Setembro,Colombo,TAG,10,14,20,atraasado
2,Setembro,Lojas 100,Figma,75,20,4,Entregue
3,Setembro,Casas Bahia,NaN,24,65,9,Atrsdo
4,Setembro,Amazon,tag,45,75,8,entrge
5,Setembro,MELI,Jsl,65,64,10,entregue
6,Setembro,LoJas 100,FIGMA,30,2,6,Entregue
7,Setembro,C_Bahia,TaG,50,64,4,AtraADO

,Mês,Cliente,Transportador,Peso,Distância (Km),Dias_Entrega,Status
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado
1,Agosto,NaN,TAG,10.0,15.0,5,atraAsaso
2,Agosto,Lojas 100,Figma,20.0,32.0,7,NaN
3,Agosto,Casas Bahia,NaN,NaN,1000.0,8,intregue
4,Agosto,Amazon,tag,85.0,95.0,15,Atrasdo
5,Agosto,MELI,Jsl,30.0,20.0,30,entregue
6,Agosto,LoJas 100,FIGMA,5.0,34.0,56,Entregue
7,Agosto,C_Bahia,TaG,1000.0,NaN,72,AtraADO
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue
9,Setembro,Colombo,TAG,10.0,14.0,20,atraasado
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue
11,Setembro,Casas Bahia,NaN,24.0,65.0,9,Atrsdo
12,Setembro,Amazon,tag,45.0,75.0,8,entrge
13,Setembro,MELI,Jsl,65.0,64.0,10,entregue
14,Setembro,LoJas 100,FIGMA,30.0,2.0,6,Entregue
15,Setembro,C_Bahia,TaG,50.0,64.0,4,AtraADO

In [104]:
display(df_geral.info())
display(df_geral.describe())
display(df_geral)

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Mês             16 non-null     str
 1   Cliente         15 non-null     str
 2   Transportador   14 non-null     str
 3   Peso            15 non-null     float64
 4   Distância (Km)  15 non-null     float64
 5   Dias_Entrega    16 non-null     int64
 6   Status          15 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 1.0 KB

None

              Peso  Distância (Km)  Dias_Entrega
count    15.000000       15.000000      16.00000
mean    102.266667      106.000000      16.87500
std     249.563753      248.772989      19.89933
min       5.000000        2.000000       2.00000
25%      22.000000       20.000000       5.75000
50%      30.000000       34.000000       8.50000
75%      62.500000       64.500000      16.25000
max    1000.000000     1000.000000      72.00000

,Mês,Cliente,Transportador,Peso,Distância (Km),Dias_Entrega,Status
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado
1,Agosto,NaN,TAG,10.0,15.0,5,atraAsaso
2,Agosto,Lojas 100,Figma,20.0,32.0,7,NaN
3,Agosto,Casas Bahia,NaN,NaN,1000.0,8,intregue
4,Agosto,Amazon,tag,85.0,95.0,15,Atrasdo
5,Agosto,MELI,Jsl,30.0,20.0,30,entregue
6,Agosto,LoJas 100,FIGMA,5.0,34.0,56,Entregue
7,Agosto,C_Bahia,TaG,1000.0,NaN,72,AtraADO
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue
9,Setembro,Colombo,TAG,10.0,14.0,20,atraasado
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue
11,Setembro,Casas Bahia,NaN,24.0,65.0,9,Atrsdo
12,Setembro,Amazon,tag,45.0,75.0,8,entrge
13,Setembro,MELI,Jsl,65.0,64.0,10,entregue
14,Setembro,LoJas 100,FIGMA,30.0,2.0,6,Entregue
15,Setembro,C_Bahia,TaG,50.0,64.0,4,AtraADO

In [105]:
#Tratamento de Info

df_geral["Cliente"]=df_geral["Cliente"].str.strip()
df_geral["Cliente"]=df_geral["Cliente"].str.title()
df_geral["Status"]=df_geral["Status"].str.strip()
df_geral["Status"]=df_geral["Status"].str.title()
df_geral["Transportador"]=df_geral["Transportador"].replace({
    "Tag": "TAG",
    "tag": "TAG",
    "TaG": "TAG",
    "jsl": "JSL",
    "Jsl": "JSL"
})
df_geral["Cliente"]=df_geral["Cliente"].replace("C_Bahia", "Casas Bahia")
df_geral["Status"]=df_geral["Status"].replace({
    "Atraasaso": "Atrasado",
    "Atrasdo": "Atrasado",
    "Atraado": "Atrasado",
    "Atraasado": "Atrasado",
    "Atrsdo": "Atrasado",
    "Intregue": "Entregue",
    "Entrge": "Entregue",
    })
df_geral["Transportador"]=df_geral["Transportador"].replace("FIGMA", "Figma")
df_geral["Status"]=df_geral["Status"].fillna("Entregue")
df_geral["Cliente"]=df_geral["Cliente"].fillna("Meli")
df_geral["Transportador"]=df_geral["Transportador"].fillna("Figma")
df_geral["Peso"]=df_geral["Peso"].fillna(30)
df_geral["Distância (Km)"]=df_geral["Distância (Km)"].fillna(50)
df_geral = df_geral.rename(columns={"Dias_Entrega":"Lead Time"})
display(df_geral)

display(df_geral.info())

,Mês,Cliente,Transportador,Peso,Distância (Km),Lead Time,Status
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado
1,Agosto,Meli,TAG,10.0,15.0,5,Atrasado
2,Agosto,Lojas 100,Figma,20.0,32.0,7,Entregue
3,Agosto,Casas Bahia,Figma,30.0,1000.0,8,Entregue
4,Agosto,Amazon,TAG,85.0,95.0,15,Atrasado
5,Agosto,Meli,JSL,30.0,20.0,30,Entregue
6,Agosto,Lojas 100,Figma,5.0,34.0,56,Entregue
7,Agosto,Casas Bahia,TAG,1000.0,50.0,72,Atrasado
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue
9,Setembro,Colombo,TAG,10.0,14.0,20,Atrasado
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue
11,Setembro,Casas Bahia,Figma,24.0,65.0,9,Atrasado
12,Setembro,Amazon,TAG,45.0,75.0,8,Entregue
13,Setembro,Meli,JSL,65.0,64.0,10,Entregue
14,Setembro,Lojas 100,Figma,30.0,2.0,6,Entregue
15,Setembro,Casas Bahia,TAG,50.0,64.0,4,Atrasado

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Mês             16 non-null     str
 1   Cliente         16 non-null     str
 2   Transportador   16 non-null     str
 3   Peso            16 non-null     float64
 4   Distância (Km)  16 non-null     float64
 5   Lead Time       16 non-null     int64
 6   Status          16 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 1.0 KB

None

In [106]:
#Nova Coluna

df_geral["Frete"] = df_geral["Peso"] * df_geral["Distância (Km)"]

display(df_geral)

,Mês,Cliente,Transportador,Peso,Distância (Km),Lead Time,Status,Frete
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado,1500.0
1,Agosto,Meli,TAG,10.0,15.0,5,Atrasado,150.0
2,Agosto,Lojas 100,Figma,20.0,32.0,7,Entregue,640.0
3,Agosto,Casas Bahia,Figma,30.0,1000.0,8,Entregue,30000.0
4,Agosto,Amazon,TAG,85.0,95.0,15,Atrasado,8075.0
5,Agosto,Meli,JSL,30.0,20.0,30,Entregue,600.0
6,Agosto,Lojas 100,Figma,5.0,34.0,56,Entregue,170.0
7,Agosto,Casas Bahia,TAG,1000.0,50.0,72,Atrasado,50000.0
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue,1800.0
9,Setembro,Colombo,TAG,10.0,14.0,20,Atrasado,140.0
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue,1500.0
11,Setembro,Casas Bahia,Figma,24.0,65.0,9,Atrasado,1560.0
12,Setembro,Amazon,TAG,45.0,75.0,8,Entregue,3375.0
13,Setembro,Meli,JSL,65.0,64.0,10,Entregue,4160.0
14,Setembro,Lojas 100,Figma,30.0,2.0,6,Entregue,60.0
15,Setembro,Casas Bahia,TAG,50.0,64.0,4,Atrasado,3200.0

In [107]:
# Map para SLA Contratado

df_geral["SLA Contratado"] = df_geral["Transportador"].map(transportadoras)


display(df_geral)

,Mês,Cliente,Transportador,Peso,Distância (Km),Lead Time,Status,Frete,SLA Contratado
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado,1500.0,10
1,Agosto,Meli,TAG,10.0,15.0,5,Atrasado,150.0,15
2,Agosto,Lojas 100,Figma,20.0,32.0,7,Entregue,640.0,25
3,Agosto,Casas Bahia,Figma,30.0,1000.0,8,Entregue,30000.0,25
4,Agosto,Amazon,TAG,85.0,95.0,15,Atrasado,8075.0,15
5,Agosto,Meli,JSL,30.0,20.0,30,Entregue,600.0,10
6,Agosto,Lojas 100,Figma,5.0,34.0,56,Entregue,170.0,25
7,Agosto,Casas Bahia,TAG,1000.0,50.0,72,Atrasado,50000.0,15
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue,1800.0,10
9,Setembro,Colombo,TAG,10.0,14.0,20,Atrasado,140.0,15
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue,1500.0,25
11,Setembro,Casas Bahia,Figma,24.0,65.0,9,Atrasado,1560.0,25
12,Setembro,Amazon,TAG,45.0,75.0,8,Entregue,3375.0,15
13,Setembro,Meli,JSL,65.0,64.0,10,Entregue,4160.0,10
14,Setembro,Lojas 100,Figma,30.0,2.0,6,Entregue,60.0,25
15,Setembro,Casas Bahia,TAG,50.0,64.0,4,Atrasado,3200.0,15

In [115]:
#Coluna Alerta

df_geral["revisar_alerta"] = (df_geral["Alerta"]=="Revisar").astype(int)
df_geral["Alerta"] = np.where(
    df_geral["Status"] == "Atrasado", "Revisar",
    np.where(df_geral["Lead Time"] > df_geral["SLA Contratado"], "Revisar", "Ok")
)

display(df_geral)

,Mês,Cliente,Transportador,Peso,Distância (Km),Lead Time,Status,Frete,SLA Contratado,Alerta,revisar_alerta
0,Agosto,Pernambucanas,JSL,25.0,60.0,2,Atrasado,1500.0,10,Revisar,1
1,Agosto,Meli,TAG,10.0,15.0,5,Atrasado,150.0,15,Revisar,1
2,Agosto,Lojas 100,Figma,20.0,32.0,7,Entregue,640.0,25,Ok,0
3,Agosto,Casas Bahia,Figma,30.0,1000.0,8,Entregue,30000.0,25,Ok,0
4,Agosto,Amazon,TAG,85.0,95.0,15,Atrasado,8075.0,15,Revisar,1
5,Agosto,Meli,JSL,30.0,20.0,30,Entregue,600.0,10,Revisar,1
6,Agosto,Lojas 100,Figma,5.0,34.0,56,Entregue,170.0,25,Revisar,1
7,Agosto,Casas Bahia,TAG,1000.0,50.0,72,Atrasado,50000.0,15,Revisar,1
8,Setembro,Pernambucanas,JSL,60.0,30.0,14,Entregue,1800.0,10,Revisar,1
9,Setembro,Colombo,TAG,10.0,14.0,20,Atrasado,140.0,15,Revisar,1
10,Setembro,Lojas 100,Figma,75.0,20.0,4,Entregue,1500.0,25,Ok,0
11,Setembro,Casas Bahia,Figma,24.0,65.0,9,Atrasado,1560.0,25,Revisar,1
12,Setembro,Amazon,TAG,45.0,75.0,8,Entregue,3375.0,15,Ok,0
13,Setembro,Meli,JSL,65.0,64.0,10,Entregue,4160.0,10,Ok,0
14,Setembro,Lojas 100,Figma,30.0,2.0,6,Entregue,60.0,25,Ok,0
15,Setembro,Casas Bahia,TAG,50.0,64.0,4,Atrasado,3200.0,15,Revisar,1

In [116]:
#Agrupar e Criar Boolenao do Alerta

df_geral["revisar_alerta"] = (df_geral["Alerta"]=="Revisar").astype(int)


resumo_transportadora = df_geral.groupby("Transportador").agg(
    frete_medio=("Frete", "mean"),
    qtd_entregas=("Cliente", "count"),
    alerta=("revisar_alerta", "sum")
).reset_index()

display(resumo_transportadora)

  Transportador   frete_medio  qtd_entregas  alerta
0         Figma   5655.000000             6       2
1           JSL   2015.000000             4       3
2           TAG  10823.333333             6       5

In [117]:
#Renomear colunas e exportar

resumo_transportadora=resumo_transportadora.rename(columns={"frete_medio": "Frete Medio"})
resumo_transportadora=resumo_transportadora.rename(columns={"qtd_entregas": "Qtd Entrega"})
resumo_transportadora=resumo_transportadora.rename(columns={"alerta": "Alerta"})

resumo_transportadora.to_csv("Resumo Transportador.csv",index=False)

display(resumo_transportadora)

  Transportador   Frete Medio  Qtd Entrega  Alerta
0         Figma   5655.000000            6       2
1           JSL   2015.000000            4       3
2           TAG  10823.333333            6       5